import { channel } from 'diagnostics_channel'
import './globals.css'
import Script from 'next/script'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Develozy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen bg-white font-poppins'>{children}
      <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js" async />
      </body>
    </html>
  )
}
